//12) Conhecido 3 números inteiros, apresente
//o resultado da multiplicação dos mesmos
algoritmo "exc12L1"

var
  n1,n2,n3:inteiro
inicio
   escreval("Digite um numero inteiro: ")
   leia(n1)
   escreval("Digite um numero inteiro: ")
   leia(n2)
   escreval("Digite um numero inteiro: ")
   leia(n3)
   
   escreval("O resultado da multiplicacao dos numeros inteiros e: ", n1*n2*n3)
fimalgoritmo
